import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/organisms/Sidebar'
import SessionProvider from '@/components/molecules/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from '../pages/api/auth/[...nextauth]'
import Login from '@/components/organisms/Login'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatGpt Clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ?(<Login/>):(
            <div className='flex'>
            
            {/** Side Bar */}
            <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem] '>   
             <Sidebar/>
            </div>
        
            {/** Client Provider - Notification */}
            <div className='bg-[#343541] flex-1'>
             {children}
            </div>
      
        </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
